spring.application.name=services

multitenancy.mtapp.master.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/financial_master?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
multitenancy.mtapp.master.datasource.username=${DB_USERNAME:root}
multitenancy.mtapp.master.datasource.password=${DB_PASSWORD:admin}
multitenancy.mtapp.master.datasource.driverClassName=com.mysql.cj.jdbc.Driver

multitenancy.mtapp.master.datasource.connectionTimeout=20000
multitenancy.mtapp.master.datasource.maxPoolSize=20
multitenancy.mtapp.master.datasource.minIdle=5
multitenancy.mtapp.master.datasource.idleTimeout=300000
multitenancy.mtapp.master.datasource.poolName=masterdb-pool-financial_master

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_HTTP:http}://${JWT_URL}/oauth2/jwks

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

eureka.client.service-url.defaultZone=${HTTP_EUREKA}://${URL_EUREKA}/eureka
eureka.instance.instance-id=${spring.application.name}:${random.int}
server.port=8083

logging.level.com.zaxxer.hikari=WARN

spring.messages.basename=messages
spring.messages.encoding=UTF-8